// Kid-friendly example sentences for each spelling word
// All sentences are appropriate for elementary school students

export const sentences = {
  // === ONE BEE (Words 1-150) ===
  "tag": "Let's play tag at recess today!",
  "send": "I will send a letter to my grandma.",
  "deck": "We played cards on the back deck.",
  "stuck": "My shoe got stuck in the mud.",
  "snug": "The baby was snug in her blanket.",
  "fish": "We saw a colorful fish at the aquarium.",
  "hold": "Please hold my hand when we cross the street.",
  "mind": "I don't mind sharing my crayons with you.",
  "stay": "Can you stay for dinner tonight?",
  "scrub": "I need to scrub my hands before eating.",
  "draw": "I like to draw pictures of animals.",
  "brown": "The puppy has soft brown fur.",
  "cozy": "My bedroom is warm and cozy.",
  "tint": "The sunset had a pink tint.",
  "milk": "I drink a glass of milk every morning.",
  "yawn": "I yawn when I am sleepy.",
  "tank": "We have a fish tank in our classroom.",
  "want": "I want to learn how to ride a bike.",
  "crowd": "There was a big crowd at the school play.",
  "pond": "The ducks swim in the pond at the park.",
  "skirt": "She wore a pretty blue skirt to the party.",
  "sharks": "We learned about sharks in science class.",
  "quilt": "Grandma made me a colorful quilt.",
  "twigs": "The bird used twigs to build its nest.",
  "taffy": "We made saltwater taffy at the beach.",
  "comfy": "This chair is so comfy to sit in.",
  "stretch": "We stretch our arms before gym class.",
  "tight": "My new shoes feel a little tight.",
  "candy": "We got candy on Halloween night.",
  "scrunch": "I scrunch up my nose when I smell something funny.",
  "ruby": "The queen wore a beautiful ruby necklace.",
  "close": "Please close the door behind you.",
  "tackle": "The football player made a great tackle.",
  "wire": "The bird sat on the telephone wire.",
  "skater": "The ice skater did a beautiful spin.",
  "giant": "We read a story about a friendly giant.",
  "bucket": "I filled my bucket with sand at the beach.",
  "chance": "Everyone deserves a chance to try.",
  "baskets": "We put the apples in baskets.",
  "tender": "The meat was cooked until it was tender.",
  "paste": "I used paste to glue my project together.",
  "melon": "We had sweet melon for a snack.",
  "farmer": "The farmer grows vegetables on his farm.",
  "parent": "My parent helped me with my homework.",
  "tail": "The dog wagged its tail happily.",
  "hockey": "My brother plays hockey every Saturday.",
  "slime": "We made green slime in science class.",
  "insects": "We found many insects in the garden.",
  "teeth": "I brush my teeth twice a day.",
  "shortcut": "We took a shortcut through the park.",
  "bait": "Dad put bait on the fishing hook.",
  "lure": "The bright colors lure butterflies to the flowers.",
  "cluster": "There was a cluster of grapes on the vine.",
  "forest": "We went hiking in the forest.",
  "hollow": "The squirrel lives in a hollow tree.",
  "spinning": "The top was spinning on the table.",
  "baffling": "The magic trick was baffling!",
  "sizzling": "The bacon was sizzling in the pan.",
  "hoist": "We watched them hoist the flag up the pole.",
  "search": "Let's search for seashells on the beach.",
  "remind": "Please remind me to bring my library book.",
  "mango": "I love to eat fresh mango in the summer.",
  "coral": "The coral reef was full of colorful fish.",
  "jangle": "I heard the keys jangle in Dad's pocket.",
  "shimmer": "The lake began to shimmer in the sunlight.",
  "blossoms": "The cherry blossoms are beautiful in spring.",
  "swampy": "The swampy area was home to many frogs.",
  "studded": "Her crown was studded with jewels.",
  "focus": "I need to focus on my reading.",
  "distress": "The lost kitten was in distress until we found it.",
  "lessons": "I take piano lessons every Tuesday.",
  "moment": "Wait just a moment please.",
  "ajar": "The door was left slightly ajar.",
  "basil": "Mom adds fresh basil to her pasta sauce.",
  "triple": "I got a triple scoop ice cream cone!",
  "satin": "The princess wore a satin dress.",
  "ahoy": "The pirate shouted ahoy from the ship!",
  "signal": "The crossing guard gave us the signal to walk.",
  "answer": "Do you know the answer to this question?",
  "shuffle": "Let me shuffle the cards before we play.",
  "dollop": "I put a dollop of whipped cream on my pie.",
  "minnows": "We saw tiny minnows swimming in the creek.",
  "silver": "The moon looked like a silver coin in the sky.",
  "before": "Wash your hands before you eat.",
  "circus": "We went to see the circus with elephants and clowns!",
  "writing": "I am writing a story about my dog.",
  "kitchen": "Mom is cooking dinner in the kitchen.",
  "sugar": "Please pass the sugar for my cereal.",
  "awkward": "It felt awkward to speak in front of everyone.",
  "seep": "Water began to seep through the crack.",
  "sweet": "The strawberries taste so sweet!",
  "wheels": "My bike has shiny new wheels.",
  "faint": "I could hear a faint sound in the distance.",
  "fruit": "I like to eat fresh fruit for breakfast.",
  "roam": "The deer roam freely in the meadow.",
  "goats": "The goats at the farm were so cute.",
  "woozy": "The spinning ride made me feel woozy.",
  "limbs": "The tree has many thick limbs to climb.",
  "ahead": "The finish line is straight ahead!",
  "señor": "We said buenos días to Señor García.",
  "unicorn": "My little sister loves unicorn stories.",
  "faraway": "She dreamed of traveling to faraway places.",
  "heater": "We turned on the heater because it was cold.",
  "pirates": "The pirates searched for buried treasure.",
  "understand": "I understand how to do this math problem now.",
  "wooden": "We sat on a wooden bench in the park.",
  "leaning": "The old tower was leaning to one side.",
  "breakfast": "I had pancakes for breakfast this morning.",
  "window": "I looked out the window and saw a rainbow.",
  "acrobat": "The acrobat did amazing flips in the air.",
  "message": "I got a message from my friend.",
  "chocolate": "I love chocolate chip cookies!",
  "forepaw": "The puppy lifted its forepaw to shake hands.",
  "elephant": "The elephant at the zoo was eating hay.",
  "hedgehog": "The hedgehog curled into a little ball.",
  "recipe": "Grandma gave me her secret cookie recipe.",
  "garbage": "Please take out the garbage after dinner.",
  "surprise": "We planned a surprise party for Mom!",
  "mermaid": "I dressed up as a mermaid for Halloween.",
  "bombarded": "We were bombarded with snowballs during the snow fight!",
  "disability": "Having a disability doesn't stop people from doing great things.",
  "incredible": "The sunset was absolutely incredible!",
  "leather": "Dad has a leather jacket.",
  "countess": "The countess lived in a beautiful castle.",
  "nervous": "I felt nervous before my first day of school.",
  "peppercorn": "A peppercorn is a tiny spice.",
  "cartwheel": "I can do a cartwheel on the grass!",
  "raise": "Please raise your hand if you have a question.",
  "weather": "The weather is perfect for a picnic today.",
  "zooming": "The cars were zooming around the racetrack.",
  "attacked": "The cat attacked its toy mouse.",
  "turnout": "There was a great turnout at the bake sale.",
  "eaten": "Have you eaten lunch yet?",
  "streetlights": "The streetlights came on when it got dark.",
  "journey": "The journey to grandma's house takes two hours.",
  "courtyard": "We played in the school courtyard.",
  "shouting": "Please stop shouting in the library.",
  "asleep": "The baby is asleep in her crib.",
  "curious": "The curious cat explored every corner.",
  "dinosaur": "My favorite dinosaur is the T-Rex!",
  "brilliant": "That was a brilliant idea!",
  "vacuum": "I helped Mom vacuum the living room.",
  "gorgeous": "The garden looked gorgeous with all the flowers.",
  "monsoon": "The monsoon brought lots of rain.",
  "dangerous": "It is dangerous to run near the pool.",
  "avocado": "I like avocado on my toast.",
  "valentine": "I made a valentine card for my friend.",
  "February": "My birthday is in February.",
  "formation": "The birds flew in a V formation.",
  "especially": "I love all fruits, especially oranges.",

  // === TWO BEE (Words 151-300) ===
  "hesitate": "Don't hesitate to ask for help.",
  "scorcher": "Today is a real scorcher, so stay cool!",
  "scavenger": "We did a scavenger hunt at the party.",
  "fragments": "The vase broke into tiny fragments.",
  "deflated": "The balloon slowly deflated overnight.",
  "unleash": "We unleash the dogs to play in the backyard.",
  "ration": "During camping, we had to ration our water.",
  "cosmetics": "My mom keeps her cosmetics in a small bag.",
  "crawdad": "We found a crawdad in the creek.",
  "frustration": "I felt frustration when I couldn't solve the puzzle.",
  "unruly": "The unruly puppy knocked over the plant.",
  "mascot": "Our school mascot is a friendly bear.",
  "aroma": "The aroma of fresh cookies filled the house.",
  "moustache": "My grandpa has a gray moustache.",
  "artifacts": "The museum has ancient artifacts from Egypt.",
  "perfume": "The flowers have a lovely perfume.",
  "sinister": "The villain in the movie had a sinister laugh.",
  "tuxedo": "Dad wore a tuxedo to the wedding.",
  "discoveries": "Scientists make amazing discoveries every day.",
  "lurches": "The old bus lurches when it stops.",
  "language": "I am learning a new language in school.",
  "prognosis": "The doctor gave a good prognosis for recovery.",
  "Buffalo": "We visited Buffalo during our road trip.",
  "sequins": "Her costume sparkled with colorful sequins.",
  "gallop": "The horse began to gallop across the field.",
  "fabulous": "We had a fabulous time at the fair.",
  "lanky": "The basketball player was tall and lanky.",
  "fluently": "She speaks Spanish fluently.",
  "mysterious": "There was a mysterious sound in the attic.",
  "brandished": "The knight brandished his sword bravely.",
  "sardines": "Dad likes to eat sardines on crackers.",
  "anguish": "She felt anguish when she lost her favorite toy.",
  "conical": "The clown wore a conical hat.",
  "rickety": "The rickety old bridge creaked as we crossed.",
  "lilt": "Her voice had a cheerful lilt to it.",
  "pediatric": "I go to the pediatric doctor for checkups.",
  "porridge": "Goldilocks ate the bear's porridge.",
  "democracy": "In a democracy, people vote for their leaders.",
  "rummage": "We had to rummage through boxes to find the toy.",
  "beige": "The walls of our house are painted beige.",
  "ancestral": "We visited our ancestral home in another country.",
  "grimace": "He made a grimace when he tasted the sour lemon.",
  "gaunt": "The lost hiker looked gaunt and tired.",
  "enormous": "We saw an enormous whale at the ocean.",
  "geranium": "Mom planted a red geranium in the pot.",
  "nautical": "The room was decorated with nautical flags.",
  "dubious": "I was dubious about the strange story.",
  "ebony": "The piano had beautiful ebony keys.",
  "foreign": "We tried food from a foreign country.",
  "paltry": "He received only a paltry amount of candy.",
  "verdict": "The jury announced their verdict.",
  "garbled": "The message was garbled and hard to understand.",
  "encourages": "My teacher encourages me to do my best.",
  "imitation": "The necklace was an imitation of real pearls.",
  "miniature": "I collect miniature cars and trucks.",
  "receptionist": "The receptionist greeted us at the front desk.",
  "preamble": "We learned about the preamble to the Constitution.",
  "plausible": "That sounds like a plausible explanation.",
  "reprimanding": "Mom was reprimanding the dog for chewing shoes.",
  "commotion": "There was a commotion when the fire alarm rang.",
  "oblivion": "The old song faded into oblivion.",
  "immigrants": "My great-grandparents were immigrants from Italy.",
  "steeple": "The church has a tall white steeple.",
  "spectators": "The spectators cheered for the home team.",
  "lanyards": "We made colorful lanyards at summer camp.",
  "suspicious": "The detective found something suspicious.",
  "parchment": "The old letter was written on parchment.",
  "ramshackle": "The ramshackle barn needed repairs.",
  "fugitive": "The movie was about catching a fugitive.",
  "heron": "A blue heron stood by the pond.",
  "dissolving": "The sugar is dissolving in the water.",
  "nomad": "A nomad travels from place to place.",
  "billowed": "The curtains billowed in the breeze.",
  "skewer": "We put vegetables on a skewer for grilling.",
  "Berlin": "Berlin is a city in Germany.",
  "lunacy": "Staying up all night was complete lunacy!",
  "conjure": "The magician could conjure a rabbit from a hat.",
  "bracken": "The bracken ferns grew thick in the forest.",
  "noggin": "Use your noggin to solve the riddle!",
  "neon": "The neon sign glowed brightly at night.",
  "rakish": "The pirate had a rakish smile.",
  "hypnosis": "The show featured a hypnosis act.",
  "rotunda": "The capitol building has a beautiful rotunda.",
  "gusto": "She sang the song with great gusto!",
  "toiletries": "Pack your toiletries in your bag for the trip.",
  "gleaned": "We gleaned information from the book.",
  "jeered": "No one should be jeered for trying their best.",
  "winsome": "The puppy had a winsome, playful personality.",
  "prattling": "The toddler was prattling happily.",
  "galore": "There were games and prizes galore at the carnival!",
  "emporium": "The toy emporium had everything we wanted.",
  "atrium": "The hotel had plants in the sunny atrium.",
  "eccentric": "Our neighbor is eccentric but very kind.",
  "savant": "The young savant could play piano beautifully.",
  "almanac": "The farmer uses an almanac to plan planting.",
  "hippies": "My grandparents told stories about hippies in the 1960s.",
  "samosas": "We ate delicious samosas at the restaurant.",
  "campaign": "The students ran a campaign to save energy.",
  "pistachio": "My favorite ice cream flavor is pistachio.",
  "mosque": "The mosque has a beautiful dome.",
  "zombielike": "I felt zombielike before my morning breakfast.",
  "warlock": "The warlock cast a spell in the story.",
  "colossus": "The ancient colossus was a giant statue.",
  "convulsively": "She laughed convulsively at the funny movie.",
  "dimensional": "We built a three-dimensional model.",
  "garishly": "The room was garishly decorated with bright colors.",
  "graffitist": "The graffitist painted murals on the wall.",
  "Everest": "Mount Everest is the tallest mountain in the world.",
  "dexterity": "The game requires a lot of dexterity.",
  "cavorting": "The puppies were cavorting in the yard.",
  "marauder": "The story featured a marauder looking for treasure.",
  "conscience": "My conscience told me to tell the truth.",
  "battlements": "The castle had tall battlements for protection.",
  "deferential": "He was deferential and polite to his elders.",
  "albatross": "The albatross has a very wide wingspan.",
  "khaki": "Dad wore khaki pants to the picnic.",
  "opalescent": "The seashell had an opalescent glow.",
  "asphalt": "The workers paved the road with asphalt.",
  "Yiddish": "My grandmother speaks Yiddish sometimes.",
  "talcum": "Baby powder is made with talcum.",
  "tranquilizer": "The vet used a tranquilizer to calm the animal.",
  "equestrian": "She competed in equestrian events with her horse.",
  "plaited": "Her hair was plaited into a pretty braid.",
  "monsieur": "We said bonjour to Monsieur Dubois.",
  "manticores": "We read about manticores in our mythology book.",
  "prestigious": "She attends a prestigious school.",
  "fraidycat": "Don't be a fraidycat, it's just a shadow!",
  "guttural": "The lion made a guttural growl.",
  "lo mein": "We ordered lo mein at the Chinese restaurant.",
  "courier": "The courier delivered the package.",
  "sans serif": "The poster used a clean sans serif font.",
  "psyche": "The story explored the character's psyche.",
  "stucco": "The house had white stucco walls.",
  "Frankenstein": "We read the story of Frankenstein in class.",
  "schema": "The teacher drew a schema to explain the idea.",
  "et cetera": "Bring pencils, erasers, et cetera to class.",
  "vidimus": "The court required a vidimus of the document.",
  "delphine": "The delphine creatures were like dolphins.",
  "slough": "The snake will slough its old skin.",
  "archipelago": "Hawaii is an archipelago of islands.",
  "serape": "He wore a colorful serape over his shoulders.",
  "puissance": "The knight showed great puissance in battle.",
  "pinioning": "The wrestler was pinioning his opponent's arms.",
  "chignon": "She styled her hair in an elegant chignon.",
  "pheromone": "Insects use pheromone to communicate.",
  "galleon": "The Spanish galleon sailed across the ocean.",
  "magnanimous": "The magnanimous winner congratulated everyone.",
  "chartreuse": "She painted her room a bright chartreuse color.",
  "wainscoting": "The dining room had beautiful wood wainscoting.",
  "Nehru": "He wore a Nehru jacket to the event.",

  // === THREE BEE (Words 301-450) ===
  "gangly": "The gangly teenager was growing so fast.",
  "swaggering": "The rooster was swaggering around the barnyard.",
  "chimneys": "Smoke rose from the chimneys in winter.",
  "riveted": "The audience was riveted by the amazing show.",
  "plaid": "Dad wore a red plaid shirt.",
  "dirge": "The sad music sounded like a dirge.",
  "zeal": "She practiced piano with great zeal.",
  "whittled": "Grandpa whittled a toy boat from wood.",
  "depots": "The trains stopped at several depots.",
  "fiberglass": "The boat was made of fiberglass.",
  "salvaged": "We salvaged parts from the old bicycle.",
  "fissures": "We saw fissures in the dried mud.",
  "enthusiastic": "The crowd was enthusiastic about the game.",
  "discipline": "It takes discipline to practice every day.",
  "unfamiliar": "The new school felt unfamiliar at first.",
  "scurrying": "Mice were scurrying across the floor.",
  "dignitaries": "Important dignitaries attended the ceremony.",
  "pizzeria": "We got pizza from the new pizzeria.",
  "dismissal": "We waited for the dismissal bell.",
  "skittish": "The skittish horse was afraid of loud noises.",
  "careened": "The shopping cart careened down the hill.",
  "nomination": "She received a nomination for the award.",
  "opportunist": "The clever fox was an opportunist.",
  "dictatorship": "We learned about what life was like under a dictatorship.",
  "comrades": "The soldiers were loyal comrades.",
  "sporadic": "We heard sporadic raindrops on the roof.",
  "promenade": "We took a promenade along the beach.",
  "repugnant": "The smell from the garbage was repugnant.",
  "invincible": "The superhero felt invincible.",
  "renowned": "The renowned artist displayed her paintings.",
  "parachute": "The skydiver's parachute opened safely.",
  "laborious": "Cleaning the whole house was laborious.",
  "appointment": "I have a dentist appointment tomorrow.",
  "foreseeable": "There's no rain in the foreseeable future.",
  "ratify": "The club members voted to ratify the new rules.",
  "scalpel": "The surgeon used a scalpel carefully.",
  "reclusive": "The reclusive author rarely left home.",
  "compassionate": "She was compassionate toward the lost puppy.",
  "bulletin": "Check the bulletin board for announcements.",
  "alfalfa": "The farmer grows alfalfa for the animals.",
  "officially": "School is officially closed for the holiday.",
  "crematorium": "The crematorium is near the cemetery.",
  "bayonet": "The museum displayed an old bayonet.",
  "amicable": "They reached an amicable agreement.",
  "exuberant": "The exuberant children ran to the playground.",
  "beautician": "The beautician styled my mom's hair.",
  "equations": "We solved math equations in class today.",
  "assignment": "I finished my homework assignment early.",
  "ultimatum": "Mom gave us an ultimatum to clean our rooms.",
  "whinnying": "We heard the horse whinnying in the stable.",
  "squalor": "The abandoned house was in squalor.",
  "memoirs": "Grandma is writing her memoirs about her life.",
  "cylinders": "The engine has four cylinders.",
  "ominous": "The dark clouds looked ominous before the storm.",
  "muffler": "The car needs a new muffler.",
  "syndrome": "The doctor explained the syndrome to us.",
  "premises": "No running on the school premises.",
  "safari": "We dreamed of going on a safari in Africa.",
  "lasagna": "Mom makes the best lasagna for dinner.",
  "substantially": "My grades improved substantially this year.",
  "mercantile": "The old mercantile store sold many things.",
  "formidable": "The opposing team was a formidable challenge.",
  "propaganda": "We learned to recognize propaganda in media.",
  "marquee": "The movie title was on the theater marquee.",
  "proficient": "She became proficient at playing chess.",
  "compunction": "He had no compunction about telling the truth.",
  "emphatically": "She emphatically agreed with the plan.",
  "hyperventilated": "I almost hyperventilated from laughing so hard.",
  "ostracism": "Ostracism means being left out of a group.",
  "onslaught": "We faced an onslaught of homework this week.",
  "ruefully": "He ruefully admitted he had made a mistake.",
  "misanthrope": "The grumpy character was a misanthrope.",
  "prototype": "The inventor built a prototype of her design.",
  "cravenly": "The coward acted cravenly in the story.",
  "mulberry": "We picked mulberry fruits from the tree.",
  "hypocritical": "It's hypocritical to say one thing and do another.",
  "chlorine": "The pool water smelled like chlorine.",
  "traumatic": "Losing a pet can be a traumatic experience.",
  "receipts": "Mom keeps all the shopping receipts.",
  "solemnly": "They solemnly promised to tell the truth.",
  "begrudge": "I don't begrudge her success.",
  "contentious": "The meeting became contentious over the rules.",
  "precocious": "The precocious child could read at age three.",
  "ensemble": "The musical ensemble performed beautifully.",
  "cadre": "A small cadre of students led the project.",
  "lye": "Lye is used in making some soaps.",
  "belfry": "The bells hung in the church belfry.",
  "lacrosse": "My sister plays lacrosse in the spring.",
  "sluice": "Water rushed through the sluice gate.",
  "cajolery": "No amount of cajolery would change her mind.",
  "vigilance": "The guard maintained vigilance all night.",
  "residuals": "The actor earned residuals from reruns.",
  "boutique": "Mom found a nice dress at the boutique.",
  "peroxide": "We used peroxide to clean the scrape.",
  "aristocracy": "The aristocracy lived in grand mansions.",
  "apocalypse": "The movie was about surviving an apocalypse.",
  "tuberculosis": "Tuberculosis was once a serious disease.",
  "barricade": "They built a barricade to block the road.",
  "confreres": "The artist met with her confreres at the gallery.",
  "anonymously": "Someone anonymously donated money to the school.",
  "unparalleled": "The view from the mountaintop was unparalleled.",
  "barrette": "She wore a sparkly barrette in her hair.",
  "chassis": "The mechanic repaired the car's chassis.",
  "junket": "The class went on a junket to the museum.",
  "quandary": "I was in a quandary about what to wear.",
  "Erie": "Lake Erie is one of the Great Lakes.",
  "gingham": "She made a dress from gingham fabric.",
  "silhouette": "We saw the silhouette of a bird against the sunset.",
  "auxiliary": "The hospital has an auxiliary power supply.",
  "thesaurus": "Use a thesaurus to find a better word.",
  "patriarchs": "The patriarchs of the family gathered for dinner.",
  "chandelier": "The beautiful chandelier sparkled in the ballroom.",
  "dulce": "We had dulce de leche for dessert.",
  "concierge": "The concierge helped us find a restaurant.",
  "latticework": "Roses grew on the garden latticework.",
  "hibiscus": "The hibiscus flowers were bright red.",
  "tamale": "Grandma taught me to make a tamale.",
  "maracas": "We shook maracas during music class.",
  "gyroplane": "A gyroplane looks like a small helicopter.",
  "burpees": "We did burpees in gym class today.",
  "Adriatic": "The Adriatic Sea is near Italy.",
  "piccolo": "She plays the piccolo in the band.",
  "au revoir": "We said au revoir to our French friends.",
  "tulle": "The ballerina's skirt was made of tulle.",
  "boll weevil": "The boll weevil is an insect that eats cotton.",
  "camphor": "Grandma's closet smelled like camphor.",
  "Tucson": "Tucson is a city in Arizona.",
  "paparazzi": "The paparazzi followed the famous singer.",
  "pumpernickel": "I like pumpernickel bread with cream cheese.",
  "pogrom": "We learned about pogroms in history class.",
  "bursitis": "The athlete was treated for bursitis.",
  "pâtisserie": "We bought croissants from the pâtisserie.",
  "cycads": "Cycads are ancient plants that look like palms.",
  "sarsaparilla": "My grandpa loves sarsaparilla soda.",
  "maître d'": "The maître d' showed us to our table.",
  "cannelloni": "We ordered cannelloni at the Italian restaurant.",
  "boulangerie": "We got fresh bread from the French boulangerie.",
  "bronchitis": "I stayed home from school with bronchitis.",
  "Oswego": "Oswego is a city in New York.",
  "diphtheria": "There is a vaccine for diphtheria.",
  "baklava": "Baklava is a sweet pastry with honey and nuts.",
  "corbels": "The shelf was supported by decorative corbels.",
  "trebuchets": "Medieval armies used trebuchets to attack castles.",
  "Kilimanjaro": "Mount Kilimanjaro is the tallest mountain in Africa.",
  "fräulein": "The word fräulein means young lady in German.",
  "protégé": "The young artist was the protégé of a famous painter.",
  "hors d'oeuvres": "We served hors d'oeuvres at the party.",
  "maquisards": "The maquisards were brave resistance fighters.",
  "Aubusson": "The Aubusson rug was very valuable.",
  "Charolais": "Charolais cattle are large and white."
};
